INSERT INTO public.quick_phrases (category, phrase, sort_order, is_active)
SELECT v.category, v.phrase, v.sort_order, true
FROM (VALUES
  ('neurotoxin', 'Product, lot number, and expiration verified prior to reconstitution; recorded in chart.', 1),
  ('neurotoxin', 'Reconstituted with preservative-free 0.9% sodium chloride per manufacturer guidelines.', 2),
  ('neurotoxin', 'Time of reconstitution documented; used within manufacturer-recommended window.', 3),
  ('neurotoxin', 'Pre-treatment photographs obtained in standardized lighting with patient consent.', 4),
  ('neurotoxin', 'Areas of intended treatment marked with patient in upright, animated position.', 5),
  ('neurotoxin', 'Skin prepped with chlorhexidine/alcohol; aseptic technique maintained throughout.', 6),
  ('neurotoxin', 'Injections placed intramuscularly using 32G needle, perpendicular technique unless noted.', 7),
  ('neurotoxin', 'Units administered per area documented in injection grid; totals verified with patient.', 8),
  ('neurotoxin', 'No vascular compromise observed; injection sites blanched appropriately and resolved.', 9),
  ('neurotoxin', 'Patient tolerated procedure well; pain scored 0–2/10; no syncope or vasovagal response.', 10),
  ('neurotoxin', 'Post-treatment instructions reviewed: avoid manipulation of area, no supine position x4h, no strenuous exercise x24h, avoid heat exposure x24h.', 11),
  ('neurotoxin', 'Counseled on expected onset 3–7 days, peak effect 2 weeks, duration 3–4 months.', 12),
  ('neurotoxin', 'Counseled on risks: bruising, headache, transient asymmetry, ptosis (brow/lid), diplopia, dry eye, dysphagia (rare), antibody formation with frequent dosing.', 13),
  ('neurotoxin', 'Two-week follow-up offered for assessment and potential touch-up within manufacturer guidance.', 14),
  ('neurotoxin', 'Patient denies pregnancy, breastfeeding, neuromuscular disease, or aminoglycoside use.', 15),
  ('neurotoxin', 'No active infection, inflammation, or open lesion at injection sites.', 16),

  ('filler', 'Product, lot number, syringe count, and expiration verified prior to injection; recorded in chart.', 1),
  ('filler', 'Pre-treatment photographs obtained in standardized lighting with patient consent.', 2),
  ('filler', 'Vascular anatomy reviewed; high-risk zones (glabella, nasolabial, temple, nose) discussed with patient.', 3),
  ('filler', 'Skin prepped with chlorhexidine; sterile field maintained throughout.', 4),
  ('filler', 'Topical anesthetic applied and removed prior to injection; lidocaine sensitivity denied.', 5),
  ('filler', 'Cannula (size/length documented) used in high-risk zones to reduce vascular event risk.', 6),
  ('filler', 'Aspiration performed prior to bolus injection in high-risk areas; negative for blood return.', 7),
  ('filler', 'Slow, low-pressure injection technique used; small aliquots delivered.', 8),
  ('filler', 'Volumes per area documented; symmetry assessed and confirmed with patient in upright mirror review.', 9),
  ('filler', 'No signs of vascular occlusion (blanching, dusky discoloration, disproportionate pain, capillary refill delay) observed during or after procedure.', 10),
  ('filler', 'Hyaluronidase, aspirin, nitroglycerin paste, and warm compresses available on site per vascular emergency protocol.', 11),
  ('filler', 'Post-treatment instructions reviewed: ice intermittently, avoid manipulation x24h, no strenuous exercise x24h, no dental work x2 weeks, no facials/lasers x2 weeks.', 12),
  ('filler', 'Counseled on expected results, integration over 2 weeks, and duration based on product/area.', 13),
  ('filler', 'Counseled on risks: bruising, swelling, asymmetry, nodules, Tyndall effect, infection, biofilm, delayed-onset nodules, vascular occlusion (rare), blindness (rare).', 14),
  ('filler', 'Vision changes, severe pain, or skin color changes — instructed to call clinic immediately and seek ER if after hours.', 15),
  ('filler', 'Two-week follow-up scheduled for assessment.', 16),
  ('filler', 'Patient denies pregnancy, breastfeeding, active infection, recent dental work, or autoimmune flare.', 17),

  ('energy', 'Device, handpiece, and settings verified; calibration confirmed prior to treatment.', 1),
  ('energy', 'Settings documented: fluence/energy, pulse duration, spot size, passes, depth, cooling.', 2),
  ('energy', 'Fitzpatrick skin type assessed; settings selected appropriate for skin type and area.', 3),
  ('energy', 'Test spot performed when clinically indicated; response assessed prior to full treatment.', 4),
  ('energy', 'Skin cleansed and dried; ultrasound gel / coupling fluid applied per device protocol.', 5),
  ('energy', 'Eye protection (wavelength-specific goggles or corneal shields) worn by patient and all staff in room.', 6),
  ('energy', 'Pre-treatment photographs obtained with patient consent.', 7),
  ('energy', 'Recent sun exposure, self-tanner, photosensitizing medications, and isotretinoin use screened — none reported within contraindicated window.', 8),
  ('energy', 'Cooling (contact / cryogen / Zimmer) used throughout; patient tolerated well, pain 0–4/10.', 9),
  ('energy', 'Clinical endpoint achieved: transient erythema / mild perifollicular edema / pinpoint bleeding / no epidermal injury.', 10),
  ('energy', 'For microneedling: single-use sterile cartridge opened in front of patient, disposed of in sharps after use.', 11),
  ('energy', 'No blistering, crusting, prolonged purpura, or epidermal injury at end of treatment.', 12),
  ('energy', 'Post-treatment instructions reviewed: broad-spectrum SPF 30+ daily, avoid direct sun and heat x48–72h, gentle cleansers, no actives x5–7 days, no waxing or exfoliation x1 week.', 13),
  ('energy', 'Counseled on expected downtime, erythema 24–72h, possible PIH risk, and timeline for results over series.', 14),
  ('energy', 'Counseled on risks: erythema, edema, blistering, crusting, post-inflammatory hyperpigmentation, hypopigmentation, scarring, infection, paradoxical hair growth (where applicable), recurrence.', 15),
  ('energy', 'Follow-up and next treatment in series scheduled per protocol.', 16),
  ('energy', 'Patient denies pregnancy, active herpetic outbreak, active infection, recent tan, or use of contraindicated medications.', 17),

  ('wellness', 'Indication, dose, route, frequency, and duration reviewed and verified prior to administration.', 1),
  ('wellness', 'Medication, lot/NDC, and expiration verified; recorded in chart.', 2),
  ('wellness', 'Baseline vitals obtained and within acceptable parameters for treatment.', 3),
  ('wellness', 'Baseline labs reviewed and within acceptable range for therapy initiation/continuation.', 4),
  ('wellness', 'Weight, BMI, waist circumference documented at this visit.', 5),
  ('wellness', 'For GLP-1/Retatrutide: titration schedule reviewed; counseled on GI side effects, hydration, protein intake, and signs of pancreatitis/gallbladder disease requiring discontinuation.', 6),
  ('wellness', 'For HRT: symptom inventory reviewed; risks of VTE, stroke, breast/endometrial concerns discussed; shared decision-making documented.', 7),
  ('wellness', 'For peptides: source, compounding pharmacy, sterility, and off-label nature disclosed; patient elected to proceed.', 8),
  ('wellness', 'Self-injection technique demonstrated and return-demonstrated; sharps disposal reviewed.', 9),
  ('wellness', 'For chemical peel: pH/acid/strength verified; skin prepped, eyes/nares protected, neutralizer and fan accessible.', 10),
  ('wellness', 'Peel applied in even passes; endpoint documented (level of frosting/erythema); neutralized per protocol.', 11),
  ('wellness', 'Post-peel instructions reviewed: bland moisturizer, strict SPF, no picking, no actives x5–7 days, expected peeling 3–7 days.', 12),
  ('wellness', 'Counseled on risks: GI intolerance, hypoglycemia (with concurrent agents), injection site reactions, hyper/hypopigmentation (peels), prolonged erythema, scarring, infection, allergic reaction.', 13),
  ('wellness', 'Drug interactions and contraindications reviewed against current medication list; none identified.', 14),
  ('wellness', 'Follow-up labs and visit scheduled per protocol; patient given contact for between-visit concerns.', 15),
  ('wellness', 'Patient denies pregnancy, breastfeeding, personal/family history of medullary thyroid carcinoma or MEN2 (where applicable), and active malignancy.', 16),

  ('compliance', 'Shared decision-making documented; patient elected to proceed after reviewing risks, benefits, and alternatives including no treatment.', 25),
  ('compliance', 'Standing order / treatment protocol on file reviewed and followed; deviations noted with rationale.', 26),
  ('compliance', 'Sharps and biohazard waste disposed of per OSHA protocol immediately after procedure.', 27),
  ('compliance', 'Single-use disposables opened in patient view; multi-use items reprocessed per manufacturer IFU.', 28),
  ('compliance', 'No solicitation of testimonial, review, or social-media post made in exchange for service or discount.', 29),
  ('compliance', 'Minor patient: parent/legal guardian present, identity verified, and consent obtained prior to treatment.', 30),
  ('compliance', 'Interpreter services offered; patient declined or used qualified interpreter — name and method documented.', 31),
  ('compliance', 'Chart reviewed and electronically signed by treating provider at conclusion of visit.', 32)
) AS v(category, phrase, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.quick_phrases qp
  WHERE qp.category = v.category AND qp.phrase = v.phrase
);